-- << 회원Table >> --

DROP TABLE "MEMBER";

-- TABLE 생성
CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER	 	PRIMARY KEY,
	"MEMBER_ID" VARCHAR2(50)  NOT NULL,
	"MEMBER_PW"	VARCHAR2(100)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NICKNAME" VARCHAR2(30) NOT NULL,
	"MEMEBER_GENDER"	CHAR(1) 	NOT NULL,
	"MEMBER_PROFILE"	VARCHAR2(300)		NULL,
	"MEMBER_ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"MEMBER_DEL_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

-- SEQUENCE 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

--------------------------------------------------------------------------------------

-- << 영화 TABLE >> --

DROP TABLE "MOVIE";

-- TABLE 생성
CREATE TABLE "MOVIE" (
	"MOVIE_NO"	NUMBER	 	PRIMARY KEY,
	"MOVIE_TITLE" VARCHAR2(100)  NOT NULL,
	"MOVIE_IMG"	VARCHAR2(300)		NOT NULL,
	"MOVIE_SUMMARY"	VARCHAR2(1000)		NOT NULL,
	"MOVIE_GENRE" VARCHAR2(50) NOT NULL,
	"MOVIE_RELEASE_DATE" DATE NOT NULL,
	"MOVIE_AGE"	VARCHAR2(20)	DEFAULT '전체관람' 	NOT NULL,
	"MOVIE_RUNNING_TIME"	NUMBER	 NOT NULL,
	"MOVIE_ENROLL_DATE"	DATE	DEFAULT SYSDATE NOT NULL,
	"MOVIE_DEL_YN" CHAR(1)	DEFAULT 'N'  NOT NULL
);

-- SEQUENCE 생성
CREATE SEQUENCE SEQ_MOVIE_NO NOCACHE;

--------------------------------------------------------------------------------------

-- << 영화관 TABLE >> --

DROP TABLE "CINEMA";

-- TABLE 생성
CREATE TABLE "CINEMA" (
	"CINEMA_NO"	NUMBER	 	PRIMARY KEY,
	"CINEMA_NAME" VARCHAR2(40)  NOT NULL,
	"CINEMA_ADDRES"	VARCHAR2(200)	 NULL,
	"CINEMA_CONTACT"	VARCHAR2(20)	 NULL,
	"CINEMA_IMG" 	VARCHAR2(300)	 NULL,
	"CINEMA_LINK"	VARCHAR2(150)	NULL,
	"CINEMA_MAX_INCLUDE"	NUMBER	 NULL,
	"CINEMA_DEL_YN"	CHAR(1)	DEFAULT 'N'  NOT NULL
);

-- SEQUENCE 생성
CREATE SEQUENCE SEQ_CINEMA_NO NOCACHE;

-----------------------------------------------------------------------------------

-- << 이벤트 홍보 TABLE >> --

DROP TABLE "EVENT_PROMOTION";

-- TABLE 생성
CREATE TABLE "EVENT_PROMOTION" (
	"EVENT_PR_NO"	NUMBER	 	PRIMARY KEY,
	"CINEMA_NO" NUMBER  NOT NULL,
	"EVENT_TITLE"	VARCHAR2(100)	 NOT NULL,
	"EVENT_CONTENT"	VARCHAR2(500)	 NOT NULL,
	"EVENT_IMG" 	VARCHAR2(300)	 NULL,
	"EVENT_URL"	VARCHAR2(150)	NULL,
	"EVENT_ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"EVENT_DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL
);

-- SEQUENCE 생성
CREATE SEQUENCE SEQ_EVENT_PR_NO NOCACHE;


--  외래키 설정
ALTER TABLE EVENT_PROMOTION ADD CONSTRAINT FK_CINEMA_NO 
    FOREIGN KEY(CINEMA_NO) REFERENCES CINEMA(CINEMA_NO);
   
   
-------------------------------------------------------------------------------------
   
 -- << 메뉴추천 TABLE >> --

DROP TABLE "MENU_RECOMMEND";

-- TABLE 생성
CREATE TABLE "MENU_RECOMMEND" (
	"MENU_RC_NO"	NUMBER	 	PRIMARY KEY,
	"SNACK_CINEMA_NO" NUMBER  NOT NULL,
	"MEMBER_NO"	NUMBER NOT NULL,
	"MENU_GRADE"	NUMBER NOT NULL,
	"MENU_CATEGORY"	VARCHAR2(30) NOT NULL
);

-- SEQUENCE 생성
CREATE SEQUENCE SEQ_MENU_RC_NO NOCACHE;


--  외래키 설정
ALTER TABLE MENU_RECOMMEND ADD CONSTRAINT FK_MENU_CINEMA_NO
    FOREIGN KEY(SNACK_CINEMA_NO) REFERENCES MENU_STATUS(SNACK_CINEMA_NO);
   
ALTER TABLE MENU_RECOMMEND ADD CONSTRAINT FK_MEMBER_NO
    FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO);
   
   
-------------------------------------------------------------------------------------
  
 -- << 영화-상영여부 TABLE >> --

DROP TABLE "MOVIE_STATUS";

-- TABLE 생성
CREATE TABLE "MOVIE_STATUS" (
	"MOVIE_STATUS_NO"	NUMBER	 	PRIMARY KEY,
	"MOVIE_NO" NUMBER  NOT NULL,
	"CINEMA_NO"	NUMBER NOT NULL
);

-- SEQUENCE 생성
CREATE SEQUENCE SEQ_MOVIE_STATUS_NO NOCACHE;


--  외래키 설정
ALTER TABLE MOVIE_STATUS ADD CONSTRAINT FK_MOVIE_STATUS_MOVIE_NO
    FOREIGN KEY(MOVIE_NO) REFERENCES MOVIE(MOVIE_NO);
   
ALTER TABLE MOVIE_STATUS ADD CONSTRAINT FK_MOVIE_STATUS_CINEMA_NO
    FOREIGN KEY(CINEMA_NO) REFERENCES CINEMA(CINEMA_NO);
   
 -------------------------------------------------------------------------------------
  
 -- << 영화관 평가 TABLE >> --

DROP TABLE "CINEMA_EVALUATION";

-- TABLE 생성
CREATE TABLE "CINEMA_EVALUATION" (
	"CINEMA_EV_NO"	NUMBER	 	PRIMARY KEY,
	"MEMBER_NO" NUMBER  NOT NULL,
	"CINEMA_NO"	NUMBER NOT NULL,
	"EVALUATION_TYPE" VARCHAR2(10) NOT NULL,
	"CINEMA_COMMENT" VARCHAR2(500) NULL,
	"CINEMA_GRADE" NUMBER NOT NULL,
	"CINEMA_EV_ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"CINEMA_EV_DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL
);

-- SEQUENCE 생성
CREATE SEQUENCE SEQ_CINEMA_EV_NO NOCACHE;


--  외래키 설정
ALTER TABLE CINEMA_EVALUATION ADD CONSTRAINT FK_CINEMA_EVALUATION_MEMBER_NO
    FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO);
   
ALTER TABLE CINEMA_EVALUATION ADD CONSTRAINT FK_CINEMA_EVALUATION_CINEMA_NO
    FOREIGN KEY(CINEMA_NO) REFERENCES CINEMA(CINEMA_NO);
   
    -------------------------------------------------------------------------------------
  
 -- << 영화관 즐겨찾기 TABLE >> --

DROP TABLE "CINEMA_LIKE";

-- TABLE 생성
CREATE TABLE "CINEMA_LIKE" (
	"CINEMA_LIKE_NO"	NUMBER	 	PRIMARY KEY,
	"MEMBER_NO" NUMBER  NOT NULL,
	"CINEMA_NO"	NUMBER NOT NULL,
	"CINEMA_LIKE_DEL_YN" CHAR(1) DEFAULT 'N' NOT NULL
);

-- SEQUENCE 생성
CREATE SEQUENCE SEQ_CINEMA_LIKE_NO NOCACHE;


--  외래키 설정
ALTER TABLE CINEMA_LIKE ADD CONSTRAINT FK_CINEMA_LIKE_MEMBER_NO
    FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO);
   
ALTER TABLE CINEMA_LIKE ADD CONSTRAINT FK_CINEMA_LIKE_CINEMA_NO
    FOREIGN KEY(CINEMA_NO) REFERENCES CINEMA(CINEMA_NO);
 
 
