
ROLLBACK;
COMMIT;
DROP TABLE MENU;


SELECT * FROM MENU m ;
SELECT * FROM CASTING c; 
SELECT * FROM EMAIL_CHECK ec;  

-- **테이블 컬럼의 조건을 바꾸고 싶을 때**
-- ALTER TABLE 테이블명 MODIFY 컬럼명 바꾸고자 하는 타입;   
-- EX) ALTER TABLE CASTING MODIFY CASTING_URL VARCHAR2(150);

------------------------------------------------------

-- 메뉴 테이블
CREATE TABLE "MENU" (
	"MENU_NO"	NUMBER		NOT NULL,
	"MENU_NAME"	VARCHAR2(50)	NOT NULL,
	"MENU_PRICE"  NUMBER	NOT NULL,
	"MENU_IMG"	VARCHAR2(300)	NOT NULL,
	"MENU_CATEGORY"	VARCHAR2(30) NOT NULL
);

ALTER TABLE "MENU" ADD CONSTRAINT "PK_MENU" PRIMARY KEY (
	"MENU_NO"
);



CREATE SEQUENCE SEQ_MENU_NO NOCACHE;

----------------------------------------------------------

--출연진 테이블
CREATE TABLE "CASTING" (
	"CASTING_NO"	NUMBER		NOT NULL,
	"CASTING_NAME"	VARCHAR2(100)	NOT NULL,
	"CASTING_URL"	VARCHAR2(150)	NOT NULL,
	"CASTING_CATEGORY"	CHAR(1)  NOT NULL
);



ALTER TABLE "CASTING" ADD CONSTRAINT "PK_CASTING" PRIMARY KEY (
	"CASTING_NO"
);

CREATE SEQUENCE SEQ_CASTING_NO NOCACHE;

----------------------------------------------------------

--이메일확인 테이블
CREATE TABLE "EMAIL_CHECK" (
	"CHECK_NO"	NUMBER		NOT NULL,
	"CHECK_KEY"	CHAR(6)	   NOT NULL,
	"CHECK_EMAIL"	VARCHAR2(30)	NOT NULL,
	"CHECK_DATE" DATE DEFAULT SYSDATE  NOT NULL
);

CREATE SEQUENCE SEQ_CHECK_NO NOCACHE;


ALTER TABLE "EMAIL_CHECK" ADD CONSTRAINT "PK_EMAIL_CHECK" PRIMARY KEY (
	"CHECK_NO"
);

---------------------------여기까지 기본 테이블(외래키 참조 X)----------------------------------

-- 외래키 참조할 때
-- 테이블명 자료형 REFERENCES 참조할 테이블명 (컬럼명)
-- OR ALTER TABLE 테이블명 ADD FOREIGN KEY(컬럼명) REFERENCES 참조할 테이블명

DROP TABLE CINEMA_PROMOTION;

--영화관 홍보
CREATE TABLE "CINEMA_PROMOTION" (
	"PROMOTION_NO"	NUMBER	 PRIMARY KEY,
	"PROMOTION_TYPE" VARCHAR2(30) NOT NULL,
	"PROMOTION_IMG"	VARCHAR2(300),
	"PROMOTION_URL" VARCHAR2(150)  NOT NULL,
	"PROMOTION_CONTENT" VARCHAR2(500) NOT NULL,
	"PROMOTION_DEL_YN" CHAR(1)  DEFAULT 'N'  NOT NULL,
	"CINEMA_NO" NUMBER  NOT NULL
);

ALTER TABLE CINEMA_PROMOTION ADD FOREIGN KEY(CINEMA_NO) REFERENCES CINEMA;


CREATE SEQUENCE SEQ_PROMOTION_NO NOCACHE;


-----------------------------------------------

-- 메뉴 판매여부(메뉴-영화관)
CREATE TABLE "MENU_STATUS" (
	"SNACK_CINEMA_NO"	NUMBER	 PRIMARY KEY,
	"SALE_YN" CHAR(1)  DEFAULT 'N'  NOT NULL,
	"CINEMA_NO" NUMBER  NOT NULL,
	"MENU_NO"   NUMBER NOT NULL
);

ALTER TABLE MENU_STATUS ADD FOREIGN KEY(CINEMA_NO) REFERENCES CINEMA;

ALTER TABLE MENU_STATUS ADD FOREIGN KEY(MENU_NO) REFERENCES MENU;

CREATE SEQUENCE SEQ_SNACK_CINEMA_NO NOCACHE;

-----------------------------------------------

-- 영화-출연진
CREATE TABLE "MOVIE_CASTING" (
	"MOVIE_CASTING_NO"	NUMBER	 PRIMARY KEY,
	"MOVIE_NO" NUMBER  NOT NULL,
	"CASTING_NO" NUMBER  NOT NULL
);


ALTER TABLE MOVIE_CASTING ADD FOREIGN KEY(MOVIE_NO) REFERENCES MOVIE;

ALTER TABLE MOVIE_CASTING ADD FOREIGN KEY(CASTING_NO) REFERENCES CASTING;

CREATE SEQUENCE SEQ_MOVIE_CASTING_NO NOCACHE;


-----------------------------------------------

DROP TABLE MOVIE_EVALUATION;

-- 영화 평가
CREATE TABLE "MOVIE_EVALUATION" (
	"MOVIE_EV_NO"	NUMBER	 PRIMARY KEY,
	"EVALUATION_CONTENT" VARCHAR2(500),
	"MOVIE_EV_ENROLL_DATE" DATE  DEFAULT SYSDATE NOT NULL,
	"MOVIE_GRADE"     NUMBER  NOT NULL,
	"MOVIE_EV_DEL_YN"    CHAR(1) DEFAULT 'N' NOT NULL,
	"MEMBER_NO" NUMBER  NOT NULL,
	"MOVIE_NO"  NUMBER  NOT NULL
);

ALTER TABLE MOVIE_EVALUATION ADD FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER;

ALTER TABLE MOVIE_EVALUATION ADD FOREIGN KEY(MOVIE_NO) REFERENCES MOVIE;

CREATE SEQUENCE SEQ_MOVIE_EV_NO NOCACHE;

-----------------------------------------------

-- 영화 즐겨찾기
CREATE TABLE "MOVIE_LIKE" (
	"MOVIE_LIKE_NO"	NUMBER	 PRIMARY KEY,
	"MOVIE_LIKE_DEL_YN"    CHAR(1) DEFAULT 'N' NOT NULL,
	"MEMBER_NO" NUMBER  NOT NULL,
	"MOVIE_NO"  NUMBER  NOT NULL
);

ALTER TABLE MOVIE_LIKE ADD FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER;

ALTER TABLE MOVIE_LIKE ADD FOREIGN KEY(MOVIE_NO) REFERENCES MOVIE;

CREATE SEQUENCE SEQ_MOVIE_LIKE_NO NOCACHE;



